services:
  ap-db:
    image: mysql:8.0
    command:
      - --collation-server=utf8mb4_0900_bin
      - --transaction-isolation=READ-COMMITTED
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: Asia/Tokyo
    ports:
      - "53306:3306"
