version: '3.8'  # Composeファイルのバージョンを指定

services:  # コンテナサービスの定義開始
  db:  # サービス名（コンテナ名）を 'db' とする
    image: mysql:8  # 使用するMySQLの公式イメージとバージョン指定
    command:  # MySQL起動時に実行するコマンド
      - --collation-server=utf8mb4_unicode_ci  # 文字コードをUTF-8に設定
      - --character-set-server=utf8mb4  # 文字セットをUTF-8に設定
    environment:  # 環境変数の設定
      MYSQL_ROOT_PASSWORD: password  # MySQLのrootユーザーのパスワード設定
      MYSQL_DATABASE: mydatabase  # 自動作成するデータベース名
      TZ: Asia/Tokyo  # タイムゾーンの設定
    ports:  # ホストとコンテナ間のポートマッピング
      - "3306:3306"  # ホストの3306ポートをコンテナの3306ポートにマッピング
    volumes:  # 永続データの保存先を定義
      - db_data:/var/lib/mysql  # MySQLのデータをホストに保存して永続化
    restart: always  # コンテナが停止した場合に自動で再起動する設定

volumes:  # 永続ボリュームの定義
  db_data:  # 'db_data'という名前のボリュームを定義
